# Generated by Django 3.0.2 on 2020-01-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rios', '0004_auto_20200126_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='river',
            new_name='name',
        ),
    ]
