# Generated by Django 3.0.1 on 2020-01-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rios', '0007_reading_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='password',
        ),
    ]
